#!/bin/sh

sed -i "s/<h4>/## /g" "$1"
sed -i "s/<\/h4>//g" "$1"
sed -i "s/<p>//g" "$1"
sed -i "s/<\/p>//g" "$1"
sed -i "s/<pre>//g" "$1"
sed -i "s/<\/pre>//g" "$1"
sed -i "s/<i>/*/g" "$1"
sed -i "s/<\/i>/*/g" "$1"
sed -i "s/<code>/``/g" "$1"
sed -i "s/<\/code>``//g" "$1"
